// Generated by https://quicktype.io

export interface CourcesResponse {
  payload: Payload[];
}

export interface Payload {
  id:              number;
  description:     string;
  iconUrl:         string;
  courseListIcon?: string;
  longDescription: string;
  category:        string;
  lessonsCount?:   number;
}
